# Generated by Django 5.0.4 on 2024-07-11 11:38

import datetime
import django.core.validators
import django.db.models.deletion
import system.validators.formatChecker
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capacitador',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nombre_capacitador', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellidos_capacitador', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('profesion', models.CharField(max_length=255, verbose_name='Profesión')),
                ('grado_academico', models.CharField(blank=True, choices=[('Bachiller', 'BACHILLER'), ('Magister', 'MAGISTER'), ('Doctor', 'DOCTOR')], max_length=15, null=True, verbose_name='Grado Académico')),
                ('descripcion_c', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('correo', models.EmailField(blank=True, max_length=255, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='system/images/capacitadores/', validators=[system.validators.formatChecker.file_size, system.validators.formatChecker.file_extension], verbose_name='Imagen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nombre_cliente', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='system/images/clientes/', validators=[system.validators.formatChecker.file_size, system.validators.formatChecker.file_extension])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Compania',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nombre_compania', models.CharField(max_length=100, verbose_name='Nombre de la compañia')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('telefono', models.CharField(max_length=9, verbose_name='Teléfono')),
                ('direccion', models.CharField(max_length=255, verbose_name='Dirección')),
                ('url_whatsapp', models.CharField(blank=True, max_length=255, null=True, verbose_name='Url Whatsapp')),
                ('url_googlemaps', models.CharField(blank=True, max_length=320, null=True, verbose_name='Url Google Maps')),
                ('historia', models.TextField(verbose_name='Acerca de')),
                ('mision', models.TextField(verbose_name='Misión')),
                ('vision', models.TextField(verbose_name='Visión')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nombre_equipo', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido_equipo', models.CharField(max_length=100, verbose_name='Apellido')),
                ('cargo', models.CharField(max_length=100, verbose_name='Cargo')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='system/images/equipo/', validators=[system.validators.formatChecker.file_size, system.validators.formatChecker.file_extension], verbose_name='Imagen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('titulo_principal', models.CharField(blank=True, max_length=100, verbose_name='Titulo principal')),
                ('nombre_boton', models.CharField(blank=True, default='#', max_length=100, verbose_name='Nombre boton')),
                ('url_boton', models.URLField(blank=True, null=True, verbose_name='Enlace boton')),
                ('sub_section_proyectos', models.TextField(blank=True, null=True, verbose_name='Subtitulo Seccion Proyectos')),
                ('sub_section_servicios', models.TextField(blank=True, null=True, verbose_name='Subtitulo Seccion Servicios')),
                ('sub_section_clientes', models.TextField(blank=True, null=True, verbose_name='Subtitulo Seccion Clientes')),
                ('sub_section_cursos', models.TextField(blank=True, null=True, verbose_name='Subtitulo Seccion Cursos')),
                ('sub_section_equipo', models.TextField(blank=True, null=True, verbose_name='Subtitulo Seccion Equipo')),
                ('imagen_mision', models.ImageField(upload_to='system/images/galeria/', validators=[system.validators.formatChecker.file_size, system.validators.formatChecker.file_extension], verbose_name='Imagen Misión')),
                ('imagen_vision', models.ImageField(upload_to='system/images/galeria/', validators=[system.validators.formatChecker.file_size, system.validators.formatChecker.file_extension], verbose_name='Imagen Visión')),
            ],
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nombre_servicio', models.CharField(max_length=100, unique=True, verbose_name='Nombre del servicio')),
                ('descripcion_servicio', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoServicio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nombre_tipo_servicio', models.CharField(max_length=100, unique=True, verbose_name='Nombre del tipo de servicio')),
            ],
        ),
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nombre_curso', models.CharField(max_length=255, unique=True, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('fecha_de_inicio', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de Inicio')),
                ('horario', models.TextField(blank=True, null=True, verbose_name='Horario')),
                ('duracion', models.TextField(blank=True, null=True, verbose_name='Duración')),
                ('costo', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Costo')),
                ('temario', models.FileField(blank=True, null=True, upload_to='system/documentos/temarios/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx'])], verbose_name='Temario')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='system/images/cursos/', validators=[system.validators.formatChecker.file_size, system.validators.formatChecker.file_extension], verbose_name='Imagen')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('capacitador_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.capacitador', verbose_name='Capacitador')),
            ],
        ),
        migrations.CreateModel(
            name='ImagenGaleria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='system/images/galeria/', validators=[system.validators.formatChecker.file_size, system.validators.formatChecker.file_extension])),
                ('galeria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='system.galeria')),
            ],
        ),
        migrations.CreateModel(
            name='Inscripciones',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nombre_ins', models.CharField(max_length=255, verbose_name='Nombre')),
                ('apellidos_ins', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('telefono', models.CharField(max_length=9, verbose_name='Teléfono')),
                ('correo', models.EmailField(max_length=255, verbose_name='Correo')),
                ('profesion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Profesión')),
                ('grado_academico', models.CharField(blank=True, choices=[('Bachiller', 'BACHILLER'), ('Magister', 'MAGISTER'), ('Doctor', 'DOCTOR')], max_length=15, null=True, verbose_name='Grado Académico')),
                ('consulta', models.TextField(max_length=150, verbose_name='Consulta')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('curso_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.cursos', verbose_name='Seleccione el curso de su interes')),
            ],
        ),
        migrations.CreateModel(
            name='Notificaciones',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('texto', models.CharField(blank=True, max_length=255, verbose_name='Mensaje')),
                ('nombre_noti', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre')),
                ('apellidos_noti', models.CharField(blank=True, max_length=100, null=True, verbose_name='Apellidos')),
                ('leido', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.cursos', verbose_name='Cursos')),
                ('inscripciones', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.inscripciones', verbose_name='Incripciones')),
            ],
        ),
        migrations.CreateModel(
            name='Proyectos',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nombre_proyecto', models.CharField(max_length=100, unique=True, verbose_name='Nombre del proyecto')),
                ('descripcion_proyecto', models.TextField(verbose_name='Descripción del proyecto')),
                ('fecha_de_proyecto', models.DateField(default=datetime.datetime.now, verbose_name='Fecha del Proyecto')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('cliente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.clientes', verbose_name='Seleccione un Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='ImagenProyectos',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='system/images/proyectos/')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='system.proyectos')),
            ],
        ),
        migrations.CreateModel(
            name='ImagenServicios',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='system/images/servicios/')),
                ('servicios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='system.servicios')),
            ],
        ),
        migrations.AddField(
            model_name='servicios',
            name='servicio_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.tiposervicio', verbose_name='Seleccione un tipo de servicio'),
        ),
    ]
